name: tantivy-jpc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
      - name: Build
        run: cargo build --release && mv target/release/libtantivy_jpc.a go-client/tantivy/packaged/lib/linux-amd64/ && cp -u target/tantivy-jpc.h go-client/tantivy/packaged/include/
      - name: Run tests
        run: cargo test --verbose
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: update linux binary
          title: Update libtantivy_jpc.a
          body: Credit new contributors by updating libtantivy_jpc.a
          branch: update-linux-binary
          delete-branch: true
          base: master
  build-mac-arm:
    permissions:
      contents: write
      pull-requests: write

    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          targets: aarch64-apple-darwin

      - name: Build for mac
        run: cargo build --release --target aarch64-apple-darwin && mv target/aarch64-apple-darwin/release/libtantivy_jpc.a go-client/tantivy/packaged/lib/darwin-aarch64/

      - name: Run tests
        run: cargo test --verbose

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: update darwin aarch lib
          title: Update libtantivy_jpc.a
          body: Credit new contributors by updating libtantivy_jpc.a
          branch: update-darwin-aarch-lib
          delete-branch: true
          base: master
